# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 23:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('userMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
